//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeuristicAlghorithmsComparer.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResultDetail()
        {
            this.Point = new HashSet<Point>();
        }
    
        public int Id { get; set; }
        public int Iterations { get; set; }
        public int FunctionEvaluations { get; set; }
        public decimal BestFunctionValue { get; set; }
        public decimal TotalTime { get; set; }
        public string TerminatedMessage { get; set; }
        public Nullable<int> ExitFlagId { get; set; }
    
        public virtual ExitFlag ExitFlag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point> Point { get; set; }
    }
}
