//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeuristicAlghorithmsComparer.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestFunction
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int DifficultyLevel { get; set; }
        public string FunctionGraphLink { get; set; }
        public int BoundRange { get; set; }
        public int Dimension { get; set; }
    }
}
