//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeuristicAlghorithmsComparer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetaheuristicResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetaheuristicResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeuristicAlghorithmsComparer.MetaheuristicResources", typeof(MetaheuristicResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BaeleFunctionFileName {
            get {
                return ResourceManager.GetString("BaeleFunctionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BohachevskyFunctionFileName {
            get {
                return ResourceManager.GetString("BohahevskyFunctionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EasomFunctionFileName {
            get {
                return ResourceManager.GetString("EasomFunctionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EggholderFunctionFileName {
            get {
                return ResourceManager.GetString("EggholderFunctionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneticAlghoritmTestFun.
        /// </summary>
        internal static string GeneticAlghoritmFileName {
            get {
                return ResourceManager.GetString("GeneticAlghoritmFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GriewankFunctionFileName {
            get {
                return ResourceManager.GetString("GriewankFunctionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba generacji:.
        /// </summary>
        internal static string LiczbaGeneracji {
            get {
                return ResourceManager.GetString("LiczbaGeneracji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba iteracji:.
        /// </summary>
        internal static string LiczbaIteracji {
            get {
                return ResourceManager.GetString("LiczbaIteracji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParticleSwarmOptimizationTestFun.
        /// </summary>
        internal static string ParticleSwarmOptimizationFileName {
            get {
                return ResourceManager.GetString("ParticleSwarmOptimizationFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RosenbrockFunctionFileName {
            get {
                return ResourceManager.GetString("RosenbrockFunctionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimulatedAnnealingTestFun.
        /// </summary>
        internal static string SimulatedAnnealingFileName {
            get {
                return ResourceManager.GetString("SimulatedAnnealingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wielkość populacji:.
        /// </summary>
        internal static string WielkoscPopulacji {
            get {
                return ResourceManager.GetString("WielkoscPopulacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wielkość roju:.
        /// </summary>
        internal static string WielkoscRoju {
            get {
                return ResourceManager.GetString("WielkoscRoju", resourceCulture);
            }
        }
    }
}
