//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeuristicAlghorithmsComparer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputParameter
    {
        public int Id { get; set; }
        public int MaxTime { get; set; }
        public int MaxIterations { get; set; }
        public int MaxFunctionEvaluations { get; set; }
        public Nullable<int> SwarmSize { get; set; }
        public Nullable<int> PopulationSize { get; set; }
        public int MaxStallIterations { get; set; }
    }
}
