//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeuristicAlghorithmsComparer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputParameter
    {
        public int Id { get; set; }
        public int LowerBoundX { get; set; }
        public int LowerBoundY { get; set; }
        public int UpperBoundX { get; set; }
        public int UpperBoundY { get; set; }
        public Nullable<decimal> StartingPointX { get; set; }
        public Nullable<decimal> StartingPointY { get; set; }
        public decimal MaxTime { get; set; }
        public int MaxIterations { get; set; }
        public int MaxFunctionEvaluations { get; set; }
        public Nullable<int> SwarmSize { get; set; }
        public Nullable<int> PopulationSize { get; set; }
    }
}
