//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeuristicAlghorithmsComparer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultDetail
    {
        public int Id { get; set; }
        public int Generations { get; set; }
        public int FunctionEvaluations { get; set; }
        public decimal BestFunctionValue { get; set; }
        public decimal FinalPointX { get; set; }
        public decimal FinalPointY { get; set; }
        public decimal TotalTime { get; set; }
        public string TerminatedMessage { get; set; }
        public Nullable<int> ExitFlagId { get; set; }
    
        public virtual ExitFlag ExitFlag { get; set; }
    }
}
